repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: gdformat
        name: gdformat
        entry: gdformat --check
        language: python
        additional_dependencies: [gdtoolkit==4.5.0]
        types: [gdscript]
        files: \.gd$

      - id: gdlint
        name: gdlint
        entry: gdlint scripts/
        language: python
        additional_dependencies: [gdtoolkit==4.5.0]
        pass_filenames: false
